version: '3'

services:
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - webserver-var:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./etc/letsencrypt/live:/etc/letsencrypt/live
      - ./var/log/letsencrypt:/var/log/letsencrypt/
      - webserver-var:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email admin@systemsdesignauthority.co.uk --agree-tos --no-eff-email --staging -d systemsdesignauthority.co.uk -d www.systemsdesignauthority.co.uk

volumes:
  certbot-etc:
  webserver-var:

networks:
  app-network:
    driver: bridge
